version: "1.0"
info:
  scaffold: Debug4WIE645
  model: int-scaffold
services:
- serviceName: pub.flow:debugLog
  packages:
  - name: WmPublic
    version: 11.0.0.0.286
- serviceName: edge.customjuly5.integrations:Debug4WIE645
  packages:
  - name: EdgeCustomJuly5
    version: "1.0"
