version: "1.0"
info:
  scaffold: EdgeCustomJuly5
  model: int-scaffold
services:
- serviceName: pub.flow:debugLog
  packages:
  - name: WmPublic
    version: 11.0.0.0.286
- serviceName: edge.customjuly5.integrations:Copy_GetMoreDates4Dave
  packages:
  - name: EdgeCustomJuly5
    version: "1.0"
- serviceName: pub.date:getCurrentDateString
  packages:
  - name: WmPublic
    version: 11.0.0.0.286
- serviceName: pub.flow:debugLog
  packages:
  - name: WmPublic
    version: 11.0.0.0.286
- serviceName: edge.customjuly5.integrations:Debug4WIE645
  packages:
  - name: EdgeCustomJuly5
    version: "1.0"
- serviceName: pub.date:currentNanoTime
  packages:
  - name: WmPublic
    version: 11.0.0.0.286
- serviceName: edge.customjuly5.integrations:dt
  packages:
  - name: EdgeCustomJuly5
    version: "1.0"
- serviceName: edge.customjuly5.javaservices.Default:Untitled_1
  packages:
  - name: EdgeCustomJuly5
    version: "1.0"
